<?php
require_once('partials/head.phtml');
?>

<title>Admin - User details</title>
</head>

<body>
<?php
require_once('partials/header.phtml');
?>

<!--Breadcrumbs-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-3 py-0 mb-3">
        <li class="breadcrumb-item" ><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">User details</li>
    </ol>
</nav>

<div class="container">
    <!--Page title block-->
    <div class="text-center">
        <h1>New user</h1>
    </div>

    <!--User details form-->
    <form action="" method="post">
        <div class="form-group">
            <label for="userName">Name</label>
            <input name="name" type="text" class="form-control" id="userName" placeholder="User name">
        </div>
        <div class="form-group">
            <label for="userEmail">Email</label>
            <input name="email" type="email" class="form-control" id="userEmail" placeholder="User email">
        </div>
        <div class="form-group">
            <label for="userPassword">Password</label>
            <input name="password" type="password" class="form-control" id="userPassword" placeholder="User password">
        </div>
        <div class="form-group">
            <label for="userRole">Role</label>
            <select name="role" class="form-control" id="userRole">
                <option selected hidden>Choose here</option>
                <option value="Admin">Admin</option>
                <option value="Candidate">Candidate</option>
            </select>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>
</body>
</html>