<?php
require_once('partials/head.phtml');
?>

    <title>Admin - Questions listing</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Questions listing</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Questions listing</h1>
        </div>

        <!--Table actions block-->
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="">
                    <label for="textSearch">Text search</label>
                    <div class="input-group">
                        <input type="text" id="textSearch" class="form-control" placeholder="">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 col-md-6 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1" href="/newQuestion">Add new question</a>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th scope="col" class="sorting-header asc dsc">ID</th>
                    <th scope="col">Text</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var $questions \QuizApp\Entity\QuestionTemplate[] */?>
                <?php foreach ($questions as $question) :?>
                <tr>
                    <?php /** @var $question \QuizApp\Entity\QuestionTemplate */?>
                    <th scope="row"><?php echo $question->getId()?></th>
                    <td><?php echo $question->getText()?></td>
                    <td><?php echo $question->getType()?></td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="/editQuestion/<?php echo $question->getId()?>">Edit</a>
                        <a class="btn btn-danger py-1" href="/deleteQuestion/<?php echo $question->getId()?>">Delete</a>
                    </td>
                </tr>
                <?php endforeach?>
                </tbody>
            </table>
        </div>

        <!--Pagination block-->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>