<?php
require_once('partials/head.phtml');
?>

    <title>Admin - Quiz details</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>
    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Quiz details</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Edit quiz</h1>
        </div>

        <!--Quiz details form-->
        <form action="" method="post">
            <div class="form-group">
                <label for="quizName">Name</label>
                <input name="name" type="text" class="form-control" id="quizName" placeholder="Quiz name" value="<?php echo $quiz->getName();?>">
            </div>
            <div class="form-group">
                <label for="quizType">Type</label>
                <input name="type" type="text" class="form-control" id="quizType" placeholder="Quiz Type" value="<?php echo $quiz->getType();?>">
            </div>
            <div class="form-group">
                <label for="quizQuestions">Questions</label>
                <select class="form-control" id="quizQuestions" multiple>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Save quiz</button>
            </div>
        </form>
    </div>
</body>
</html>