<?php
require_once('partials/head.phtml');
?>

<title>Admin - Quiz details</title>
</head>

<body>
<?php
require_once('partials/header.phtml');
?>
<!--Breadcrumbs-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-3 py-0 mb-3">
        <li class="breadcrumb-item" ><a href="/admin/dashboard">Dashboard</a></li>
        <li class="breadcrumb-item" ><a href="/listQuizzes">Quizzes</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add Quiz</li>
    </ol>
</nav>

<div class="container">
    <!--Page title block-->
    <div class="text-center">
        <h1>New quiz</h1>
    </div>

    <!--Quiz details form-->
    <form action="" method="post">
        <div class="form-group">
            <label for="quizName">Name</label>
            <input name="name" type="text" class="form-control" id="quizName" placeholder="Quiz name">
        </div>
        <div class="form-group">
            <label for="quizType">Type</label>
            <input name="type" type="text" class="form-control" id="quizType" placeholder="Quiz Type">
        </div>
        <div class="form-group">
            <label for="quizQuestions">Questions</label>
            <select name="questions[]" class="form-control" id="quizQuestions" multiple>
                <?php /** @var $questions \QuizApp\Entity\QuestionTemplate[] */?>
                <?php foreach ($questions->getItems() as $question) :?>
                <option value="<?php echo $question->getId()?>"><?php echo $question->getText()?></option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Save quiz</button>
        </div>
    </form>
</div>
</body>
</html>