<?php
require_once('partials/head.phtml');
?>

    <title>Admin - Questions listing</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="/admin/dashboard">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Questions listing</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Questions listing</h1>
        </div>

        <!--Table actions block-->
        <div class="row">
            <div class="col-12 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1" href="/newQuestion">Add new question</a>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th scope="col">ID</th>
                    <th scope="col">Text</th>
                    <th scope="col">Type</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var $questions \QuizApp\Entity\QuestionTemplate[] */?>
                <?php foreach ($questions as $question) :?>
                <tr>
                    <?php /** @var $question \QuizApp\Entity\QuestionTemplate */?>
                    <th scope="row"><?php echo $question->getId()?></th>
                    <td><?php echo $question->getText()?></td>
                    <td><?php echo $question->getType()?></td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="/editQuestion/<?php echo $question->getId()?>">Edit</a>
                        <a class="btn btn-danger py-1" href="/deleteQuestion/<?php echo $question->getId()?>">Delete</a>
                    </td>
                </tr>
                <?php endforeach?>
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>