<?php
require_once('partials/head.phtml');
?>
    <title>Admin - Question details</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Question details</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Edit question</h1>
        </div>

        <!--Question details form-->
        <form action="" method="post">
            <div class="form-group">
                <label for="questionText">Question text</label>
                <textarea name="text" class="form-control" id="questionText" placeholder="Question text"><?php echo $question->getText();?></textarea>
            </div>
            <div class="form-group">
                <label for="questionType">Question type</label>
                <select name="type" class="form-control" id="questionType" multiple >
                    <option value="Text" <?php if($question->getType() == 'Text'){echo("selected");}?>>Text</option>
                    <option value="Code" <?php if($question->getType() == 'Code'){echo("selected");}?>>Code</option>
                </select>
            </div>
            <div class="form-group">
                <label for="answerText">Answer text</label>
                <textarea name="text" class="form-control" id="answerText" placeholder="Answer text"></textarea>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Save question</button>
            </div>
        </form>
    </div>
</body>
</html>