<?php
require_once('partials/head.phtml');
?>

    <title>Admin - Users listing</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="#">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Users listing</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Users listing</h1>
        </div>

        <!--Table actions block-->
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="">
                    <div class="form-group">
                        <label for="roleSearch">User role select</label>
                        <select class="form-control" id="roleSearch">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="col-12 col-md-6 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1 mb-3" href="#">Add new user</a>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th scope="col" class="sorting-header asc dsc">ID</th>
                    <th scope="col">Email</th>
                    <th scope="col">Name</th>
                    <th scope="col">Role</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>asd asad asdadadsad</td>
                    <td>azxczxc cxzc</td>
                    <td>1</td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="#">Edit</a>
                        <a class="btn btn-danger py-1" href="#">Delete</a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>asd asad asdadadsad</td>
                    <td>azxczxc cxzc</td>
                    <td>2</td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="#">Edit</a>
                        <a class="btn btn-danger py-1" href="#">Delete</a>
                    </td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>asd asad asdadadsad</td>
                    <td>azxczxc cxzc</td>
                    <td>3</td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="#">Edit</a>
                        <a class="btn btn-danger py-1" href="#">Delete</a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

        <!--Pagination block-->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>