<?php
require_once('partials/head.phtml');
?>

    <title>Admin - Quizzes listing</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="/admin/dashboard">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Quizzes listing</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center pb-3">
            <h1>Quizzes</h1>
        </div>


        <!--Table actions block-->
        <div class="row">
            <div class="col-12 col-md-6">
                <form action="/listQuizzes" method="get">
                    <label for="quizSearch">Quiz name search</label>
                    <div class="input-group">
                        <input name="name" type="text" id="quizSearch" class="form-control" placeholder="">
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-12 col-md-6 d-flex align-items-end justify-content-end">
                <a class="btn btn-primary py-1" href="/newQuiz">Add new quiz</a>
            </div>
        </div>

        <!--Quiz listing table-->
        <div class="table-responsive my-4">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                    <th scope="col">ID</th>
                    <th scope="col">Quiz</th>
                    <th scope="col">Type</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var $quizzes \QuizApp\Entity\QuizTemplate[] */?>
                <?php foreach ($quizzes as $quiz) :?>
                <tr>
                    <?php /** @var $quiz \QuizApp\Entity\QuizTemplate */?>
                    <th scope="row"><?php echo $quiz->getId()?></th>
                    <td><?php echo $quiz->getName()?></td>
                    <td><?php echo $quiz->getType()?></td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="/editQuiz/<?php echo $quiz->getId()?>">Edit</a>
                        <a class="btn btn-danger py-1" href="/deleteQuiz/<?php echo $quiz->getId()?>">Delete</a>
                    </td>
                </tr>
                <?php endforeach?>
                </tbody>
            </table>
        </div>

        <!--Pagination block-->
        <nav aria-label="Page navigation example">
            <?php if ($paginator->getTotalResults() > $paginator->getResultsPerPage()):
                $currentPage = $paginator->getCurrentPage();
                ?>
                <ul class="pagination justify-content-center">
                    <li class="page-item <?php if ($currentPage === 1) echo 'disabled'; ?>">
                        <a class="page-link"
                           href="?page=<?php echo $currentPage-1; ?>">Previous</a>
                    </li>
                    <?php for ($pageNumber = 1; $pageNumber <= $paginator->getTotalPages(); $pageNumber++): ?>
                        <li class="page-item <?php if ($currentPage === $pageNumber) echo 'active'; ?>">
                            <a class="page-link" href="?page=<?php echo $pageNumber; ?>">
                                <?php echo $pageNumber; ?>
                            </a>
                        </li>
                    <?php endfor; ?>
                    <li class="page-item <?php if ($currentPage === $paginator->getTotalPages()) echo 'disabled'; ?>">
                        <a class="page-link" href="?page=<?php echo $paginator->getNextPage(); ?>">
                            Next
                        </a>
                    </li>
                </ul>
            <?php endif; ?>
        </nav>
    </div>
</body>
</html>