<?php
require_once('partials/head.phtml');
?>
<title>Admin - Question details</title>
</head>

<body>
<?php
require_once('partials/header.phtml');
?>

<!--Breadcrumbs-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-3 py-0 mb-3">
        <li class="breadcrumb-item" ><a href="/admin/dashboard">Dashboard</a></li>
        <li class="breadcrumb-item" ><a href="/listQuestions">Questions</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add Question</li>
    </ol>
</nav>

<div class="container">
    <!--Page title block-->
    <div class="text-center">
        <h1>Add question</h1>
    </div>

    <!--Question details form-->
    <form action="" method="post">
        <div class="form-group">
            <label for="questionText">Question text</label>
            <textarea name="text" class="form-control" id="questionText" placeholder="Question text"></textarea>
        </div>
        <div class="form-group">
            <label for="questionType">Question type</label>
            <select name="type" class="form-control" id="questionType">
                <option selected hidden>Choose here</option>
                <option value="Text">Text</option>
                <option value="Code">Code</option>
            </select>
        </div>
        <div class="form-group">
            <label for="answerText">Answer text</label>
            <textarea name="answer" class="form-control" id="answerText" placeholder="Answer text"></textarea>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Save question</button>
        </div>
    </form>
</div>
</body>
</html>