<?php
require_once('partials/head.phtml');
?>

    <title>Candidate - Quizzes listing</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>
    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item active" aria-current="page"><a href="#">Homepage</a></li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Quizzes</h1>
        </div>

        <!--Quizzes listing-->
        <table class="table table-hover my-4">
            <thead>
            <tr>
                <th scope="col">Quiz name</th>
                <th scope="col">Quiz type</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php /** @var $quizzes \QuizApp\Entity\QuizTemplate[] */?>
            <?php foreach ($quizzes as $quiz) :?>
            <tr>
                <?php /** @var $quiz \QuizApp\Entity\QuizTemplate */?>
                <th scope="row"><?php echo $quiz->getName()?></th>
                <td><?php echo $quiz->getType()?></td>
                <td class="text-center">
                    <a class="btn btn-primary py-1" href="/start/quiz/<?php echo $quiz->getId()?>">Start quiz</a>
                </td>
            </tr>
            <?php endforeach?>
            </tbody>
        </table>
    </div>

    <!--Pagination block-->
    <nav aria-label="Page navigation example">
        <?php if ($paginator->getTotalResults() > 5):
            $currentPage = $paginator->getCurrentPage();
            ?>
            <ul class="pagination justify-content-center">
                <li class="page-item <?php if ($currentPage === 1) echo 'disabled'; ?>">
                    <a class="page-link"
                       href="?page=<?php echo $currentPage-1; ?>">Previous</a>
                </li>
                <?php for ($pageNumber = 1; $pageNumber <= $paginator->getTotalPages(); $pageNumber++): ?>
                    <li class="page-item <?php if ($currentPage === $pageNumber) echo 'active'; ?>">
                        <a class="page-link" href="?page=<?php echo $pageNumber; ?>">
                            <?php echo $pageNumber; ?>
                        </a>
                    </li>
                <?php endfor; ?>
                <li class="page-item <?php if ($currentPage === $paginator->getTotalPages()) echo 'disabled'; ?>">
                    <a class="page-link" href="?page=<?php echo $paginator->getNextPage(); ?>">
                        Next
                    </a>
                </li>
            </ul>
        <?php endif; ?>
    </nav>
</body>
</html>