<?php
require_once('partials/head.phtml');
?>

    <title>Candidate - Quiz page</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="/candidate/homepage">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Quiz page</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
<!--        <div class="text-center">-->
<!--            --><?php ///** @var $quiz \QuizApp\Entity\QuizInstance */?>
<!--            <h1>--><?php //echo $quiz->getName()?><!--</h1>-->
<!--        </div>-->

        <!--Quiz form-->
        <div class="">
            <?php /** @var $question \QuizApp\Entity\QuestionInstance */?>
            <p class="font-weight-bold"><?php echo $question->getText()?></p>
        </div>
        <form action="" method="get">
            <div class="form-group">
                <?php /** @var $answer \QuizApp\Entity\AnswerInstance */?>
                <textarea name="answer" class="form-control" id="questionResponse" placeholder="<?php echo $answer->getText()?>"></textarea>
            </div>
            <div class="text-center">
                <?php if($questionInstanceIndex != 1): ?>
                <button formmethod="get" formaction="/quiz/question/<?php echo $questionInstanceIndex-1?>" type="submit" class="btn btn-primary">Previous</button> /
                <?php endif; ?>
                <?php if(!$isLastQuestion):?>
                <button formmethod="post" formaction="/user/answer/<?php echo $answer->getId()?>/<?php echo $questionInstanceIndex?>" type="submit" class="btn btn-primary">Next</button>
                <?php else: ?>
                <button formmethod="post" formaction="/user/answer/<?php echo $answer->getId()?>" type="submit" class="btn btn-primary">Save</button>
                <?php endif; ?>
            </div>
        </form>
    </div>
</body>
</html>