<?php

use QuizApp\ViewModel\AnsweredQuestion;

require_once('partials/head.phtml');
?>
<!--Code Highlight Library css-->
<link rel="stylesheet" href="/assets/css/colors-css.css">

<title>Candidate - Overview</title>
</head>

<body>
<?php
require_once('partials/header.phtml');
?>

<!--Breadcrumbs-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-3 py-0 mb-3">
        <li class="breadcrumb-item"><a href="/candidate/homepage">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Results</li>
    </ol>
</nav>

<div class="container">
    <!--Page title block-->
    <div class="text-center pb-3">
        <h1><?php echo $quizInstance->getName() ?></h1>
    </div>

    <div class="row">
        <div class="col-md-8 order-md-1 ">
            <!--Quiz block-->
            <?php foreach ($answeredQuestions as $answeredQuestion): ?>
                <div class="card border-secondary mb-3">
                    <div class="card-header">
                        <p class="mb-1">Question: </p>
                        <?php /** @var $answeredQuestion AnsweredQuestion */ ?>
                        <span><?php echo $answeredQuestion->getQuestion()->getText() ?></span>
                    </div>
                    <div class="card-body">
                        <p class="mb-1">Answer: </p>
                        <span><?php echo $answeredQuestion->getAnswer()->getText() ?></span>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <div class="col-md-4 order-md-2 mb-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Go to:</span>
            </h4>
            <ul class="list-group mb-3">
                <?php $questionIndex = 1; ?>
                <?php foreach ($answeredQuestions as $answeredQuestion): ?>
                    <li class="list-group-item border-secondary">
                        <a href="/quiz/question/<?php echo $questionIndex ?>"><?php echo $answeredQuestion->getQuestion()->getText() ?></a>
                    </li>
                    <?php $questionIndex++; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <!--Results form-->
    <form action="" method="get">
        <div class="text-center">
            <button formmethod="get" formaction="/quiz/question/<?php echo $lastQuestionIndex?>" type="submit" class="btn btn-primary">Back</button> /
            <button formmethod="get" formaction="/candidate/success" type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
</div>
</body>
</html>