<?php
require_once('partials/head.phtml');
?>

    <title>Candidate - Quizzes listing</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>
    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item active" aria-current="page"><a href="#">Dashboard</a></li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Quizzes</h1>
        </div>

        <!--Quizzes listing-->
        <table class="table table-hover my-4">
            <thead>
            <tr>
                <th scope="col">Quiz name</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">ASd dsadsada asdadads</th>
                <td class="text-center">
                    <a class="btn btn-primary py-1" href="#">Start quiz</a>
                </td>
            </tr>
            <tr>
                <th scope="row">asdasddas asdaddasd</th>
                <td class="text-center">
                    <a class="btn btn-primary py-1" href="#">Start quiz</a>
                </td>            </tr>
            <tr>
                <th scope="row">ZXC sadasd asdasdadas</th>
                <td class="text-center">
                    <a class="btn btn-primary py-1" href="#">Start quiz</a>
                </td>            </tr>
            </tbody>
        </table>
    </div>

    <!--Pagination block-->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>
</body>
</html>