<?php
require_once('partials/head.phtml');
?>

    <title>Candidate - Quiz success page</title>
</head>

<body>
    <?php
        require_once('partials/header.phtml');
    ?>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="/candidate/homepage">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Quiz success page</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>Congrats!</h1>
            <img src="../../public/assets/img/giphy.gif" alt="">
        </div>
    </div>
</body>
</html>